//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveToGameWpf.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveToGameWpf.Resources.Localizations.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрый режим.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код активации:.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление данных.
        /// </summary>
        public static string AddingData {
            get {
                return ResourceManager.GetString("AddingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные настройки.
        /// </summary>
        public static string AdditionalParameters {
            get {
                return ResourceManager.GetString("AdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альтернативный метод подписи.
        /// </summary>
        public static string AlternativeSigning {
            get {
                return ResourceManager.GetString("AlternativeSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте эту опцию, если возникают ошибки во время работы готового приложения.
        /// </summary>
        public static string AlternativeSigningToolTip {
            get {
                return ResourceManager.GetString("AlternativeSigningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.androeed.ru.
        /// </summary>
        public static string Androeed_ru {
            get {
                return ResourceManager.GetString("Androeed_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Андроид файлы.
        /// </summary>
        public static string AndroidFiles {
            get {
                return ResourceManager.GetString("AndroidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveToGame.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивы.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сохранения.
        /// </summary>
        public static string BackupType {
            get {
                return ResourceManager.GetString("BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить про версию.
        /// </summary>
        public static string BuyFullVersion {
            get {
                return ResourceManager.GetString("BuyFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы кэша.
        /// </summary>
        public static string CacheFiles {
            get {
                return ResourceManager.GetString("CacheFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить сообщение из файла.
        /// </summary>
        public static string Cant_add_popup_message_from_file {
            get {
                return ResourceManager.GetString("Cant_add_popup_message_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить сохранить в файл. Попробуйте сделать это вручную.
        /// </summary>
        public static string Cant_add_save {
            get {
                return ResourceManager.GetString("Cant_add_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось проверить ключ.
        /// </summary>
        public static string Cant_check_the_key {
            get {
                return ResourceManager.GetString("Cant_check_the_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить временную папку..
        /// </summary>
        public static string Cant_delete_temp_folder {
            get {
                return ResourceManager.GetString("Cant_delete_temp_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось активировать программу.
        /// </summary>
        public static string Cant_make_program_pro {
            get {
                return ResourceManager.GetString("Cant_make_program_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обновлении программы.
        /// </summary>
        public static string Cant_update_program {
            get {
                return ResourceManager.GetString("Cant_update_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл (apk).
        /// </summary>
        public static string ChooseApk {
            get {
                return ResourceManager.GetString("ChooseApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл лицензии.
        /// </summary>
        public static string ChooseLicense {
            get {
                return ResourceManager.GetString("ChooseLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать сохранение.
        /// </summary>
        public static string ChooseSave {
            get {
                return ResourceManager.GetString("ChooseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование приложения.
        /// </summary>
        public static string CopyingApk {
            get {
                return ResourceManager.GetString("CopyingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование программы StG.
        /// </summary>
        public static string CopyingStgApk {
            get {
                return ResourceManager.GetString("CopyingStgApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалять окно apkmania.
        /// </summary>
        public static string DeleteApkmaniaWindow {
            get {
                return ResourceManager.GetString("DeleteApkmaniaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчик:.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержать:.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта скопирована в буфер обмена.
        /// </summary>
        public static string Email_was_copied {
            get {
                return ResourceManager.GetString("Email_was_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА.
        /// </summary>
        public static string ErrorUp {
            get {
                return ResourceManager.GetString("ErrorUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл или сохранение не выбраны!.
        /// </summary>
        public static string File_or_save_not_selected {
            get {
                return ResourceManager.GetString("File_or_save_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иконки.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия с доп. файлом.
        /// </summary>
        public static string InstallApkVersion {
            get {
                return ResourceManager.GetString("InstallApkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить java.
        ///Причина: &quot;{0}&quot;.
        ///Попробовать ещё раз?.
        /// </summary>
        public static string JavaDownloadFailed {
            get {
                return ResourceManager.GetString("JavaDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка java.
        /// </summary>
        public static string JavaDownloading {
            get {
                return ResourceManager.GetString("JavaDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковка файлов java.
        /// </summary>
        public static string JavaExtracting {
            get {
                return ResourceManager.GetString("JavaExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая версия java может вызывать ошибки при работе программы. Будет загружена версия, работающая корректно.
        /// </summary>
        public static string JavaInvalidVersion {
            get {
                return ResourceManager.GetString("JavaInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string Loading_Title {
            get {
                return ResourceManager.GetString("Loading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МБ.
        /// </summary>
        public static string Mb {
            get {
                return ResourceManager.GetString("Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество показов сообщения: {0}.
        /// </summary>
        public static string MessagesCount {
            get {
                return ResourceManager.GetString("MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модификация завершена.
        /// </summary>
        public static string ModificationCompletedContent {
            get {
                return ResourceManager.GetString("ModificationCompletedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещение готового файла.
        /// </summary>
        public static string MovingResult {
            get {
                return ResourceManager.GetString("MovingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет необходимых файлов для корректной работы программы!
        ///Отсутствующие файлы: {0}.
        /// </summary>
        public static string NoNeededFilesError {
            get {
                return ResourceManager.GetString("NoNeededFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоторые файлы не найдены!.
        /// </summary>
        public static string Not_enough_files {
            get {
                return ResourceManager.GetString("Not_enough_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает уведомление об окончании процесса модификации.
        /// </summary>
        public static string NotificationsTooltip {
            get {
                return ResourceManager.GetString("NotificationsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только сообщение.
        /// </summary>
        public static string OnlyMessage {
            get {
                return ResourceManager.GetString("OnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только сохранение.
        /// </summary>
        public static string OnlySave {
            get {
                return ResourceManager.GetString("OnlySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу:.
        /// </summary>
        public static string Path_to_file {
            get {
                return ResourceManager.GetString("Path_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время работы возникла ошибка, связанная с превышением допустимой длины имени файла. Дайте файлам короткие названия и переместите их поближе к корню диска.
        /// </summary>
        public static string PathTooLongExceptionMessage {
            get {
                return ResourceManager.GetString("PathTooLongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена: 100 руб.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация программы.
        /// </summary>
        public static string ProgramActivation {
            get {
                return ResourceManager.GetString("ProgramActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Задание текста всплывающего сообщения
        ///- Возможность указать расположение главного smali файла (файла с методом onCreate). Может понадобиться, если программа не может найти его сама
        ///- Встраивание кеша с использованием контейнера
        ///- Добавление иконки и названия конечного файла к контейнеру.
        /// </summary>
        public static string ProVersionPlusses {
            get {
                return ResourceManager.GetString("ProVersionPlusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение + сообщение.
        /// </summary>
        public static string SavePlusMessage {
            get {
                return ResourceManager.GetString("SavePlusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Странно, обнаружены неизвестные ошибки....
        /// </summary>
        public static string Some_Error_Found {
            get {
                return ResourceManager.GetString("Some_Error_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление данных.
        /// </summary>
        public static string StepAddingData {
            get {
                return ResourceManager.GetString("StepAddingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка проекта.
        /// </summary>
        public static string StepCompiling {
            get {
                return ResourceManager.GetString("StepCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декомпиляция.
        /// </summary>
        public static string StepDecompiling {
            get {
                return ResourceManager.GetString("StepDecompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка.
        /// </summary>
        public static string StepInitializing {
            get {
                return ResourceManager.GetString("StepInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление баннеров.
        /// </summary>
        public static string StepRemovingBanners {
            get {
                return ResourceManager.GetString("StepRemovingBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замена текстов.
        /// </summary>
        public static string StepReplacingTexts {
            get {
                return ResourceManager.GetString("StepReplacingTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись файла.
        /// </summary>
        public static string StepSigning {
            get {
                return ResourceManager.GetString("StepSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поблагодарить:.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения:.
        /// </summary>
        public static string TextOfMessage {
            get {
                return ResourceManager.GetString("TextOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за покупку!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия активирована. Спасибо за покупку.
        /// </summary>
        public static string ThanksPurchase {
            get {
                return ResourceManager.GetString("ThanksPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёмная.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка!.
        /// </summary>
        public static string Unknown_error {
            get {
                return ResourceManager.GetString("Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена непредвиденная ошибка.
        /// </summary>
        public static string UnknownErrorOccured {
            get {
                return ResourceManager.GetString("UnknownErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимы права администратора. Продолжить?.
        /// </summary>
        public static string UpdateAdminRequired {
            get {
                return ResourceManager.GetString("UpdateAdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия. Обновить?.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия. Обновить?.
        /// </summary>
        public static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер счёта (WMR) скопирован в буфер обмена.
        /// </summary>
        public static string WebMoneyWmrCopied {
            get {
                return ResourceManager.GetString("WebMoneyWmrCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер счёта (WMZ) скопирован в буфер обмена.
        /// </summary>
        public static string WebMoneyWmzCopied {
            get {
                return ResourceManager.GetString("WebMoneyWmzCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш код:.
        /// </summary>
        public static string YourCode {
            get {
                return ResourceManager.GetString("YourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip архивы.
        /// </summary>
        public static string ZipArchives {
            get {
                return ResourceManager.GetString("ZipArchives", resourceCulture);
            }
        }
    }
}
