//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveToGameWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveToGameWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на www.androeed.ru.
        /// </summary>
        public static string Androeed_ru {
            get {
                return ResourceManager.GetString("Androeed_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SaveToGame.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить сообщение из файла.
        /// </summary>
        public static string Cant_add_popup_message_from_file {
            get {
                return ResourceManager.GetString("Cant_add_popup_message_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить сохранить в файл. Попробуйте сделать это вручную.
        /// </summary>
        public static string Cant_add_save {
            get {
                return ResourceManager.GetString("Cant_add_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось проверить ключ.
        /// </summary>
        public static string Cant_check_the_key {
            get {
                return ResourceManager.GetString("Cant_check_the_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить временную папку..
        /// </summary>
        public static string Cant_delete_temp_folder {
            get {
                return ResourceManager.GetString("Cant_delete_temp_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось активировать программу.
        /// </summary>
        public static string Cant_make_program_pro {
            get {
                return ResourceManager.GetString("Cant_make_program_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обновлении программы.
        /// </summary>
        public static string Cant_update_program {
            get {
                return ResourceManager.GetString("Cant_update_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронная почта скопирована в буфер обмена.
        /// </summary>
        public static string Email_was_copied {
            get {
                return ResourceManager.GetString("Email_was_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл или сохранение не выбраны!.
        /// </summary>
        public static string File_or_save_not_selected {
            get {
                return ResourceManager.GetString("File_or_save_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта лицензия не действительна.
        /// </summary>
        public static string Invalid_license_fullbtn {
            get {
                return ResourceManager.GetString("Invalid_license_fullbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Java не найдена. Необходимо загрузить её с официального сайта. Ссылка скопирована в буфер обмена.
        /// </summary>
        public static string JavaNotFound {
            get {
                return ResourceManager.GetString("JavaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некоторые файлы не найдены!.
        /// </summary>
        public static string Not_enough_files {
            get {
                return ResourceManager.GetString("Not_enough_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу: .
        /// </summary>
        public static string Path_to_file {
            get {
                return ResourceManager.GetString("Path_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание текста всплывающего сообщения
        ///
        ///Возможность указать расположение главного smali файла (файла с методом onCreate). Может понадобиться, если программа не может найти его сама
        ///
        ///Встраивание кеша с использованием контейнера.
        /// </summary>
        public static string ProVersionPlusses {
            get {
                return ResourceManager.GetString("ProVersionPlusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Странно, обнаружены неизвестные ошибки....
        /// </summary>
        public static string Some_Error_Found {
            get {
                return ResourceManager.GetString("Some_Error_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо за покупку!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла неизвестная ошибка!.
        /// </summary>
        public static string Unknown_error {
            get {
                return ResourceManager.GetString("Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна новая версия. Обновить?.
        /// </summary>
        public static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
    }
}
