//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveToGameWpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveToGameWpf.Resources.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoke-static {p0, v1, v2}, Lcom/savegame/SavesRestoringPortable;-&gt;SmartDataRestoreForYou(Landroid/content/Context;Landroid/content/res/AssetManager;Ljava/lang/String;)V.
        /// </summary>
        internal static string DataRestoreCall {
            get {
                return ResourceManager.GetString("DataRestoreCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	invoke-static/range {p0 .. p0}, Lcom/savegame/SavesRestoringPortable;-&gt;DoSmth(Landroid/content/Context;)V
        ///
        ///.
        /// </summary>
        internal static string MainSmaliCall {
            get {
                return ResourceManager.GetString("MainSmaliCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	const-string v0, &quot;[(message)]&quot;
        ///
        ///	const/4 v1, 0x1
        ///
        ///    invoke-static {p0, v0, v1}, Landroid/widget/Toast;-&gt;makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
        ///
        ///    move-result-object v0
        ///
        ///    invoke-virtual {v0}, Landroid/widget/Toast;-&gt;show()V
        ///
        ///.
        /// </summary>
        internal static string MessageShow {
            get {
                return ResourceManager.GetString("MessageShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .class public final Lcom/savegame/SavesRestoringPortable;
        ///.super Landroid/app/Activity;
        ///.source &quot;SavesRestoringPortable.java&quot;
        ///
        ///
        ///# static fields
        ///.field private static PdsjdolaSd:I
        ///
        ///.field private static daDakdsIID:I
        ///
        ///
        ///# direct methods
        ///.method static constructor &lt;clinit&gt;()V
        ///    .locals 1
        ///
        ///    .prologue
        ///    const/4 v0, 0x0
        ///
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;PdsjdolaSd:I
        ///
        ///	const/16 v0, 0x[(message_length)]
        ///	
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;daDakdsIID:I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SavesRestoring_new {
            get {
                return ResourceManager.GetString("SavesRestoring_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .class public final Lcom/savegame/SavesRestoringPortable;
        ///.super Landroid/app/Activity;
        ///.source &quot;SavesRestoringPortable.java&quot;
        ///
        ///
        ///# static fields
        ///.field private static PdsjdolaSd:I
        ///
        ///.field private static daDakdsIID:I
        ///
        ///
        ///# direct methods
        ///.method static constructor &lt;clinit&gt;()V
        ///    .locals 1
        ///
        ///    .prologue
        ///    const/4 v0, 0x0
        ///
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;PdsjdolaSd:I
        ///
        ///	const/16 v0, 0x[(message_length)]
        ///
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;daDakdsIID:I        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SavesRestoringPortable {
            get {
                return ResourceManager.GetString("SavesRestoringPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .class public final Lcom/savegame/SavesRestoringPortable;
        ///.super Landroid/app/Activity;
        ///.source &quot;SavesRestoringPortable.java&quot;
        ///
        ///
        ///# static fields
        ///.field private static PdsjdolaSd:I
        ///
        ///.field private static daDakdsIID:I
        ///
        ///
        ///# direct methods
        ///.method static constructor &lt;clinit&gt;()V
        ///    .locals 1
        ///
        ///    .prologue
        ///    const/4 v0, 0x0
        ///
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;PdsjdolaSd:I
        ///
        ///	const/16 v0, 0x[(message_length)]
        ///
        ///    sput v0, Lcom/savegame/SavesRestoringPortable;-&gt;daDakdsIID:I        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SavesRestoringPortable___Backup {
            get {
                return ResourceManager.GetString("SavesRestoringPortable___Backup", resourceCulture);
            }
        }
    }
}
